# Generated by Django 5.0.14 on 2025-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maloprodaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Godina', models.CharField(max_length=255)),
                ('Kvartal', models.CharField(max_length=255)),
                ('Mesec', models.CharField(max_length=255)),
                ('SifraMPOB', models.IntegerField()),
                ('NazivMPOB', models.CharField(max_length=255)),
                ('NadgrupaN', models.CharField(max_length=255)),
                ('GrupaN', models.CharField(max_length=255)),
                ('PodgrupaN', models.CharField(max_length=255)),
                ('PodpodgrupaN', models.CharField(max_length=255)),
                ('SifraArt', models.IntegerField()),
                ('BarArt', models.BigIntegerField()),
                ('NazivArt', models.CharField(max_length=255)),
                ('PKolicina', models.IntegerField()),
                ('PVPDV', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'maloprodaja',
                'managed': False,
            },
        ),
    ]
